version: "3"
services:
  typo3:
    build: ./src
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - fileadmin_volume:/app/public/fileadmin
      - typo3conf_volume:/app/typo3conf
    depends_on:
      - database
  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    env_file:
      - config/db.env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/dump:/docker-entrypoint-initdb.d

volumes:
  fileadmin_volume: {}
  typo3conf_volume: {}
  db_data: {}

