version: "3"
services:
  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    env_file:
      - config/db.env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}

